### ISSUE TITLE
Adjust title header tags

### ISSUE THREAD

**Issue by pheeria** [Lernwerkstatt/site#171]
All of header tags should be semantically ordered.

Check [here](https://wave.webaim.org/report#/https://die-lernwerkstatt.org/) for more details.

**Comment by hikes101** [comment]
@pheeria I understand why the header tags schould be ordered, however, that still changes the size of the titles as far as I know. What am I missing there?

**Comment by pheeria** [comment]
Nothing prevents us from overriding `h1`, `h2`, etc. `font-size` values 😉

**Comment by hikes101** [comment]
Alright, but do you mean to change it inline then? Changing it in style.css wouldn't really help I think...

**Comment by hikes101** [comment]
@pheeria Alright, but do you mean to change it inline then? Changing it in style.css wouldn't really help I think...

**Comment by pheeria** [comment]
@hikes101 why not? We just need to make sure that our styles are included after the bootstrap ones. @jarjan any suggestions, objections?

**Comment by hikes101** [comment]
@pheeria just because we used the header tags all over the place for different size titles. if we actually order it semantically we would have to use inline styles to not change the look of the site. 
e.g. some titles are `h5` now, but should actually be `h2`. Some other titles are `h2` now and should stay that way. if we just change it in `styles.css` then at least one of them would end up looking different

**Comment by pheeria** [comment]
This is exactly what this issue is about. We need to use headers everywhere semantically, and if there is a place, like say for calendar events, where the size should be different, then use a paragraph tag.

**Comment by jarjan** [comment]
@hikes101 @pheeria there are special class name to rewrite styling for headings, such as `h1`,  `h2`, ...
More: https://getbootstrap.com/docs/4.3/content/typography/

So doing semantically correct should not be hard.
