### ISSUE TITLE
Translate "Our Values" tab on the homepage instead of having both languages

### ISSUE THREAD

**Issue by danielstreif** [Lernwerkstatt/site#224]
@pheeria @jarjan Simply using the i18n json doesn't work since the tab information is described in `home.js`. Any idea how to work around this? Here the code snippet:

```js
const ourValues = () => ({
  badge: "Über Uns",
  title: "Unsere Werte / Our Values",
  text: "Dafür steht Die Lernwerkstatt.",
  link: "/values",
  image: "img/home/notebook.png"
});
```

**Comment by pheeria** [comment]
The easiest, although not the cleanest, solution would be reading incoming cookies.
You can access them under `req.cookies`, and our language cookie is called `locale`. So, because `ourValues` is a function, you could pass `req.cookies.locale` to it and conditionally decide what text to return in each case.
